### ISSUE TITLE
2 import statements in "spec.ts" file

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/5-startit-movie-finder-EduardPopenko#5]
```
 browser, element, By, $$, $, by, Key
```
Objects are imported twice in "spec.ts" file in root folder.

it is not allowed to have Duplicate identifiers.

**Comment by EduardPopenko** [comment]
In which particular file? I checked, there is no duplication anywhere.

**Comment by alexanderpavlovets** [comment]
https://github.com/StartITProtractorJS/5-startit-movie-finder-EduardPopenko/blob/master/spec.ts

File spec.ts in root folder 

Lines 1 and 170

**Comment by EduardPopenko** [comment]
fixed
